import { definePreset } from '@primeng/themes';
import Aura from '@primeng/themes/aura';

const cascadeFigmaVariables = {
  cascadeAlias: {
    primary: '#294cf6',
    secondary: '#9773ee',
    tertiary: '#00cdd1',
    warning: '#ffd449',
    error: '#fd0052',
    neutral: '#98a8bc',
    highlight: '#ffe592',
    disabled: '#dee1e5',
  },
  cascadeBrand: {
    purpleLightest: '#d5c7f8',
    purpleLighter: '#c1abf5',
    purpleLight: '#ac8ff1',
    purple: '#9773ee',
    purpleDark: '#795cbe',
    purpleDarker: '#5b458f',
    purpleDarkest: '#3c2e5f',
    blueLightest: '#a9b7fb',
    blueLighter: '#7f94fa',
    blueLight: '#5470f8',
    blue: '#294cf6',
    tealLightest: '#99ebed',
    tealLighter: '#66e1e3',
    tealLight: '#33d7da',
    teal: '#00cdd1',
    blueDark: '#213dc5',
    blueDarker: '#192e94',
    blueDarkest: '#101e62',
    tealDark: '#00a4a7',
    tealDarker: '#007b7d',
    tealDarkest: '#005254',
    greyLightest: '#f9f9f9',
    greyLighter: '#efefef',
    greyLight: '#dee1e5',
    grey: '#98a8bc',
    greyDark: '#5b6b7f',
    greyDarkest: '#001738',
    white: '#ffffff',
    redLightest: '#fe99ba',
    redLighter: '#fe6697',
    redLight: '#fd3375',
    red: '#fd0052',
    redDark: '#ca0042',
    redDarker: '#980031',
    redDarkest: '#650021',
    goldLightest: '#ffeeb6',
    goldLighter: '#ffe592',
    goldLight: '#ffdd6d',
    gold: '#ffd449',
    goldDark: '#ccaa3a',
    goldDarker: '#997f2c',
    goldDarkest: '#66551d',
    borderNone: 0,
    spacingLarge: 32,
    spacingMedium: 16,
    spacingExtraLarge: 40,
    spacingSmall: 8,
    spacingMicro: 2,
    border: 1,
    borderMedium: 2,
    borderThick: 3,
    fontSizeSmallest: 11,
    fontSizeSmall: 12,
    fontSizeRegular: 14,
    fontSizeLarge: 16,
    fontSizeLarger: 32,
    fontSizeLargest: 48,
    fontLight: 'Light',
    fontRegular: 'Regular',
    fontBold: 'Bold',
    fontSemiBold: 'SemiBold',
    fontExtraBold: 'ExtraBold',
    fontStrong: 'Strong',
    fontFamilySecondary: 'Inter',
    fontFamilyPrimary: 'Hanken Grotesk',
    fontFamilyAlternative: 'Open Sans',
    radiusSmallest: 2,
    radiusSmall: 4,
    radius: 8,
    radiusLarge: 14,
    radiusLargest: 16,
    radiusNone: 0,
    lineHeightLarger: 32,
    lineHeightLarge: 16,
    lineHeightSmall: 12,
    lineHeightLargest: 48,
    lineHeightRegular: 14,
    lineHeightSmallest: 11,
    spacingNone: 0,
    spacingExtraSmall: 4,
    iconWidthSmall: 16,
    iconHeightSmall: 16,
    iconHeight: 32,
    iconWidth: 32,
    opacityFull: 100,
    opacityPartial: 80,
    opacityMedium: 64,
    opacityLight: 24,
    opacityLightest: 16,
    opacityNone: 0,
    iconHeightSmallest: 12,
    iconWidthSmallest: 12,
    blueLightest10: '#e9edfe',
  },
  cascadeMapped: {
    textAction: '#294cf6',
    textError: '#fd0052',
    textInformation: '#9773ee',
    textWarning: '#ffd449',
    iconWarning: '#ffd449',
    iconInformation: '#9773ee',
    iconError: '#fd0052',
    iconAction: '#294cf6',
    iconNeutral: '#98a8bc',
    textNeutral: '#98a8bc',
    textActionHover: '#213dc5',
    iconActionHover: '#213dc5',
    textDisabled: '#dee1e5',
    iconDisabled: '#dee1e5',
    buttonPrimaryHover: '#213dc5',
    buttonPrimary: '#294cf6',
    buttonPrimaryText: '#f9f9f9',
    buttonRadius: 4,
    buttonPillRadius: 16,
    buttonPrimaryAction: '#294cf6',
    buttonSecondaryAction: '#001738',
    buttonSecondaryText: '#98a8bc',
    buttonSecondaryHover: '#001738',
    buttonSecondary: '#98a8bc',
    checkSelected: '#294cf6',
    checkIconSelected: '#ffffff',
    checkDeselected: '#98a8bc',
    checkIconDeselected: '#ffffff',
    tabSelected: '#9773ee',
    tabTextSelected: '#ffffff',
    tabPaddingX: 16,
    tabPaddingY: 8,
  },
};

const Cascade = definePreset(Aura, {
  primitive: {
    gray: {
      50: cascadeFigmaVariables.cascadeBrand.greyLightest,
      100: cascadeFigmaVariables.cascadeBrand.greyLighter,
      200: cascadeFigmaVariables.cascadeBrand.greyLight,
      300: cascadeFigmaVariables.cascadeBrand.grey,
      400: cascadeFigmaVariables.cascadeBrand.greyDark,
      500: cascadeFigmaVariables.cascadeBrand.greyDarkest,
      600: cascadeFigmaVariables.cascadeBrand.greyDarkest,
      700: cascadeFigmaVariables.cascadeBrand.greyDarkest,
      800: cascadeFigmaVariables.cascadeBrand.greyDarkest,
      900: cascadeFigmaVariables.cascadeBrand.greyDarkest,
      950: cascadeFigmaVariables.cascadeBrand.greyDarkest,
    },
    purple: {
      50: cascadeFigmaVariables.cascadeBrand.purpleLightest,
      100: cascadeFigmaVariables.cascadeBrand.purpleLighter,
      200: cascadeFigmaVariables.cascadeBrand.purpleLight,
      300: cascadeFigmaVariables.cascadeBrand.purple,
      400: cascadeFigmaVariables.cascadeBrand.purpleDark,
      500: cascadeFigmaVariables.cascadeBrand.purpleDarker,
      600: cascadeFigmaVariables.cascadeBrand.purpleDarker,
      700: cascadeFigmaVariables.cascadeBrand.purpleDarkest,
      800: cascadeFigmaVariables.cascadeBrand.purpleDarkest,
      900: cascadeFigmaVariables.cascadeBrand.purpleDarkest,
      950: cascadeFigmaVariables.cascadeBrand.purpleDarkest,
    },
    sky: {
      50: cascadeFigmaVariables.cascadeBrand.blueLightest10,
      100: cascadeFigmaVariables.cascadeBrand.blueLightest10,
      200: cascadeFigmaVariables.cascadeBrand.blueLightest,
      300: cascadeFigmaVariables.cascadeBrand.blueLighter,
      400: cascadeFigmaVariables.cascadeBrand.blueLight,
      500: cascadeFigmaVariables.cascadeBrand.blue,
      600: cascadeFigmaVariables.cascadeBrand.blueDark,
      700: cascadeFigmaVariables.cascadeBrand.blueDarker,
      800: cascadeFigmaVariables.cascadeBrand.blueDarker,
      900: cascadeFigmaVariables.cascadeBrand.blueDarker,
      950: cascadeFigmaVariables.cascadeBrand.blueDarkest,
    },
    blue: {
      50: cascadeFigmaVariables.cascadeBrand.blueLightest10,
      100: cascadeFigmaVariables.cascadeBrand.blueLightest10,
      200: cascadeFigmaVariables.cascadeBrand.blueLightest,
      300: cascadeFigmaVariables.cascadeBrand.blueLighter,
      400: cascadeFigmaVariables.cascadeBrand.blueLight,
      500: cascadeFigmaVariables.cascadeBrand.blue,
      600: cascadeFigmaVariables.cascadeBrand.blueDark,
      700: cascadeFigmaVariables.cascadeBrand.blueDarker,
      800: cascadeFigmaVariables.cascadeBrand.blueDarker,
      900: cascadeFigmaVariables.cascadeBrand.blueDarker,
      950: cascadeFigmaVariables.cascadeBrand.blueDarkest,
    },
    red: {
      50: cascadeFigmaVariables.cascadeBrand.redLightest,
      100: cascadeFigmaVariables.cascadeBrand.redLighter,
      200: cascadeFigmaVariables.cascadeBrand.redLight,
      300: cascadeFigmaVariables.cascadeBrand.red,
      400: cascadeFigmaVariables.cascadeBrand.redDark,
      500: cascadeFigmaVariables.cascadeBrand.redDarker,
      600: cascadeFigmaVariables.cascadeBrand.redDarker,
      700: cascadeFigmaVariables.cascadeBrand.redDarkest,
      800: cascadeFigmaVariables.cascadeBrand.redDarkest,
      900: cascadeFigmaVariables.cascadeBrand.redDarkest,
      950: cascadeFigmaVariables.cascadeBrand.redDarkest,
    },
    gold: {
      50: cascadeFigmaVariables.cascadeBrand.goldLightest,
      100: cascadeFigmaVariables.cascadeBrand.goldLighter,
      200: cascadeFigmaVariables.cascadeBrand.goldLight,
      300: cascadeFigmaVariables.cascadeBrand.gold,
      400: cascadeFigmaVariables.cascadeBrand.goldDark,
      500: cascadeFigmaVariables.cascadeBrand.goldDarker,
      600: cascadeFigmaVariables.cascadeBrand.goldDarker,
      700: cascadeFigmaVariables.cascadeBrand.goldDarkest,
      800: cascadeFigmaVariables.cascadeBrand.goldDarkest,
      900: cascadeFigmaVariables.cascadeBrand.goldDarkest,
      950: cascadeFigmaVariables.cascadeBrand.goldDarkest,
    },
    teal: {
      50: cascadeFigmaVariables.cascadeBrand.tealLightest,
      100: cascadeFigmaVariables.cascadeBrand.tealLighter,
      200: cascadeFigmaVariables.cascadeBrand.tealLight,
      300: cascadeFigmaVariables.cascadeBrand.teal,
      400: cascadeFigmaVariables.cascadeBrand.tealDark,
      500: cascadeFigmaVariables.cascadeBrand.tealDarker,
      600: cascadeFigmaVariables.cascadeBrand.tealDarker,
      700: cascadeFigmaVariables.cascadeBrand.tealDarkest,
      800: cascadeFigmaVariables.cascadeBrand.tealDarkest,
      900: cascadeFigmaVariables.cascadeBrand.tealDarkest,
      950: cascadeFigmaVariables.cascadeBrand.tealDarkest,
    },
    yellow: {
      50: cascadeFigmaVariables.cascadeBrand.goldLightest,
      100: cascadeFigmaVariables.cascadeBrand.goldLighter,
      200: cascadeFigmaVariables.cascadeBrand.goldLight,
      300: cascadeFigmaVariables.cascadeBrand.gold,
      400: cascadeFigmaVariables.cascadeBrand.goldDark,
      500: cascadeFigmaVariables.cascadeBrand.goldDarker,
      600: cascadeFigmaVariables.cascadeBrand.goldDarker,
      700: cascadeFigmaVariables.cascadeBrand.goldDarkest,
      800: cascadeFigmaVariables.cascadeBrand.goldDarkest,
      900: cascadeFigmaVariables.cascadeBrand.goldDarkest,
      950: cascadeFigmaVariables.cascadeBrand.goldDarkest,
    },
  },
  semantic: {
    formField: {
      paddingX:
        cascadeFigmaVariables.cascadeMapped.tabPaddingX.toString() + 'px',
      paddingY:
        cascadeFigmaVariables.cascadeMapped.tabPaddingY.toString() + 'px',
      fontSize:
        cascadeFigmaVariables.cascadeBrand.fontSizeRegular.toString() + 'px',
      sm: {
        fontSize:
          cascadeFigmaVariables.cascadeBrand.fontSizeRegular.toString() + 'px',
        paddingX:
          cascadeFigmaVariables.cascadeBrand.spacingSmall.toString() + 'px',
        paddingY:
          cascadeFigmaVariables.cascadeBrand.spacingExtraSmall.toString() +
          'px',
      },
      lg: {
        fontSize:
          cascadeFigmaVariables.cascadeBrand.fontSizeLarge.toString() + 'px',
        paddingX:
          cascadeFigmaVariables.cascadeMapped.tabPaddingX.toString() + 'px',
        paddingY:
          cascadeFigmaVariables.cascadeMapped.tabPaddingY.toString() + 'px',
      },
      borderRadius:
        cascadeFigmaVariables.cascadeBrand.radiusSmall.toString() + 'px',
    },
    primary: {
      50: cascadeFigmaVariables.cascadeBrand.blueLightest10,
      100: cascadeFigmaVariables.cascadeBrand.blueLightest10,
      200: cascadeFigmaVariables.cascadeBrand.blueLightest,
      300: cascadeFigmaVariables.cascadeBrand.blueLighter,
      400: cascadeFigmaVariables.cascadeBrand.blueLight,
      500: cascadeFigmaVariables.cascadeBrand.blue,
      600: cascadeFigmaVariables.cascadeBrand.blueDark,
      700: cascadeFigmaVariables.cascadeBrand.blueDarker,
      800: cascadeFigmaVariables.cascadeBrand.blueDarker,
      900: cascadeFigmaVariables.cascadeBrand.blueDarker,
      950: cascadeFigmaVariables.cascadeBrand.blueDarkest,
    },
    secondary: {
      50: cascadeFigmaVariables.cascadeBrand.purpleLightest,
      100: cascadeFigmaVariables.cascadeBrand.purpleLighter,
      200: cascadeFigmaVariables.cascadeBrand.purpleLight,
      300: cascadeFigmaVariables.cascadeBrand.purple,
      400: cascadeFigmaVariables.cascadeBrand.purpleDark,
      500: cascadeFigmaVariables.cascadeBrand.purpleDarker,
      600: cascadeFigmaVariables.cascadeBrand.purpleDarker,
      700: cascadeFigmaVariables.cascadeBrand.purpleDarkest,
      800: cascadeFigmaVariables.cascadeBrand.purpleDarkest,
      900: cascadeFigmaVariables.cascadeBrand.purpleDarkest,
      950: cascadeFigmaVariables.cascadeBrand.purpleDarkest,
    },
    danger: {
      50: cascadeFigmaVariables.cascadeBrand.redLightest,
      100: cascadeFigmaVariables.cascadeBrand.redLighter,
      200: cascadeFigmaVariables.cascadeBrand.redLight,
      300: cascadeFigmaVariables.cascadeBrand.red,
      400: cascadeFigmaVariables.cascadeBrand.redDark,
      500: cascadeFigmaVariables.cascadeBrand.redDarker,
      600: cascadeFigmaVariables.cascadeBrand.redDarker,
      700: cascadeFigmaVariables.cascadeBrand.redDarkest,
      800: cascadeFigmaVariables.cascadeBrand.redDarkest,
      900: cascadeFigmaVariables.cascadeBrand.redDarkest,
      950: cascadeFigmaVariables.cascadeBrand.redDarkest,
    },
    warning: {
      50: cascadeFigmaVariables.cascadeBrand.goldLightest,
      100: cascadeFigmaVariables.cascadeBrand.goldLighter,
      200: cascadeFigmaVariables.cascadeBrand.goldLight,
      300: cascadeFigmaVariables.cascadeBrand.gold,
      400: cascadeFigmaVariables.cascadeBrand.goldDark,
      500: cascadeFigmaVariables.cascadeBrand.goldDarker,
      600: cascadeFigmaVariables.cascadeBrand.goldDarker,
      700: cascadeFigmaVariables.cascadeBrand.goldDarkest,
      800: cascadeFigmaVariables.cascadeBrand.goldDarkest,
      900: cascadeFigmaVariables.cascadeBrand.goldDarkest,
      950: cascadeFigmaVariables.cascadeBrand.goldDarkest,
    },
    success: {
      50: cascadeFigmaVariables.cascadeBrand.tealLightest,
      100: cascadeFigmaVariables.cascadeBrand.tealLighter,
      200: cascadeFigmaVariables.cascadeBrand.tealLight,
      300: cascadeFigmaVariables.cascadeBrand.teal,
      400: cascadeFigmaVariables.cascadeBrand.tealDark,
      500: cascadeFigmaVariables.cascadeBrand.tealDarker,
      600: cascadeFigmaVariables.cascadeBrand.tealDarker,
      700: cascadeFigmaVariables.cascadeBrand.tealDarkest,
      800: cascadeFigmaVariables.cascadeBrand.tealDarkest,
      900: cascadeFigmaVariables.cascadeBrand.tealDarkest,
      950: cascadeFigmaVariables.cascadeBrand.tealDarkest,
    },
    info: {
      50: cascadeFigmaVariables.cascadeBrand.purpleLightest,
      100: cascadeFigmaVariables.cascadeBrand.purpleLighter,
      200: cascadeFigmaVariables.cascadeBrand.purpleLight,
      300: cascadeFigmaVariables.cascadeBrand.purple,
      400: cascadeFigmaVariables.cascadeBrand.purpleDark,
      500: cascadeFigmaVariables.cascadeBrand.purpleDarker,
      600: cascadeFigmaVariables.cascadeBrand.purpleDarker,
      700: cascadeFigmaVariables.cascadeBrand.purpleDarkest,
      800: cascadeFigmaVariables.cascadeBrand.purpleDarkest,
      900: cascadeFigmaVariables.cascadeBrand.purpleDarkest,
      950: cascadeFigmaVariables.cascadeBrand.purpleDarkest,
    },
    colorScheme: {
      light: {
        surface: {
          50: cascadeFigmaVariables.cascadeBrand.greyLightest,
          100: cascadeFigmaVariables.cascadeBrand.greyLighter,
          200: cascadeFigmaVariables.cascadeBrand.greyLight,
          300: cascadeFigmaVariables.cascadeBrand.grey,
          400: cascadeFigmaVariables.cascadeBrand.greyDark,
          500: cascadeFigmaVariables.cascadeBrand.greyDarkest,
          600: cascadeFigmaVariables.cascadeBrand.greyDarkest,
          700: cascadeFigmaVariables.cascadeBrand.greyDarkest,
          800: cascadeFigmaVariables.cascadeBrand.greyDarkest,
          900: cascadeFigmaVariables.cascadeBrand.greyDarkest,
          950: cascadeFigmaVariables.cascadeBrand.greyDarkest,
        },
      },
    },
  },
});

export { Cascade, cascadeFigmaVariables };
