import { definePreset } from '@primeng/themes';
import Aura from '@primeng/themes/aura';

const cascadeFigmaVariables = {
  goldLight: '#ffdd6d',
  red: '#fd0052',
  goldDarker: '#997f2c',
  tealDarkest: '#005254',
  goldDark: '#ccaa3a',
  blueLightest10: '#e9edfe',
  purpleDark: '#795cbe',
  purpleDarkest: '#3c2e5f',
  gold: '#ffd449',
  redDarkest: '#650021',
  redDark: '#ca0042',
  blueLighter: '#7f94fa',
  redLightest: '#fe99ba',
  redLight: '#fd3375',
  blueLightest: '#a9b7fb',
  redLighter: '#fe6697',
  teal: '#00cdd1',
  purpleDarker: '#5b458f',
  blueLight: '#5470f8',
  tealDarker: '#007b7d',
  purpleLighter: '#c1abf5',
  white: '#ffffff',
  greyLightest: '#f9f9f9',
  blueDarker: '#192e94',
  grey: '#98a8bc',
  blueDark: '#213dc5',
  greyLighter: '#efefef',
  purpleLight: '#ac8ff1',
  goldLighter: '#ffe592',
  tealDark: '#00a4a7',
  greyDark: '#5b6b7f',
  tealLightest: '#99ebed',
  goldLightest: '#ffeeb6',
  purple: '#9773ee',
  purpleLightest: '#d5c7f8',
  greyDarkest: '#001738',
  tealLighter: '#66e1e3',
  blueDarkest: '#101e62',
  tealLight: '#33d7da',
  redDarker: '#980031',
  greyLight: '#dee1e5',
  blue: '#294cf6',
  goldDarkest: '#66551d',
};

const Cascade = definePreset(Aura, {
  primitive: {
    gray: {
      50: cascadeFigmaVariables.greyLightest,
      100: cascadeFigmaVariables.greyLighter,
      200: cascadeFigmaVariables.greyLight,
      300: cascadeFigmaVariables.grey,
      400: cascadeFigmaVariables.greyDark,
      500: cascadeFigmaVariables.greyDarkest,
      600: cascadeFigmaVariables.greyDarkest,
      700: cascadeFigmaVariables.greyDarkest,
      800: cascadeFigmaVariables.greyDarkest,
      900: cascadeFigmaVariables.greyDarkest,
      950: cascadeFigmaVariables.greyDarkest,
    },
    purple: {
      50: cascadeFigmaVariables.purpleLightest,
      100: cascadeFigmaVariables.purpleLighter,
      200: cascadeFigmaVariables.purpleLight,
      300: cascadeFigmaVariables.purple,
      400: cascadeFigmaVariables.purpleDark,
      500: cascadeFigmaVariables.purpleDarker,
      600: cascadeFigmaVariables.purpleDarker,
      700: cascadeFigmaVariables.purpleDarkest,
      800: cascadeFigmaVariables.purpleDarkest,
      900: cascadeFigmaVariables.purpleDarkest,
      950: cascadeFigmaVariables.purpleDarkest,
    },
    sky: {
      50: cascadeFigmaVariables.blueLightest10,
      100: cascadeFigmaVariables.blueLightest10,
      200: cascadeFigmaVariables.blueLightest,
      300: cascadeFigmaVariables.blueLighter,
      400: cascadeFigmaVariables.blueLight,
      500: cascadeFigmaVariables.blue,
      600: cascadeFigmaVariables.blueDark,
      700: cascadeFigmaVariables.blueDarker,
      800: cascadeFigmaVariables.blueDarker,
      900: cascadeFigmaVariables.blueDarker,
      950: cascadeFigmaVariables.blueDarkest,
    },
    blue: {
      50: cascadeFigmaVariables.blueLightest10,
      100: cascadeFigmaVariables.blueLightest10,
      200: cascadeFigmaVariables.blueLightest,
      300: cascadeFigmaVariables.blueLighter,
      400: cascadeFigmaVariables.blueLight,
      500: cascadeFigmaVariables.blue,
      600: cascadeFigmaVariables.blueDark,
      700: cascadeFigmaVariables.blueDarker,
      800: cascadeFigmaVariables.blueDarker,
      900: cascadeFigmaVariables.blueDarker,
      950: cascadeFigmaVariables.blueDarkest,
    },
    red: {
      50: cascadeFigmaVariables.redLightest,
      100: cascadeFigmaVariables.redLighter,
      200: cascadeFigmaVariables.redLight,
      300: cascadeFigmaVariables.red,
      400: cascadeFigmaVariables.redDark,
      500: cascadeFigmaVariables.redDarker,
      600: cascadeFigmaVariables.redDarker,
      700: cascadeFigmaVariables.redDarkest,
      800: cascadeFigmaVariables.redDarkest,
      900: cascadeFigmaVariables.redDarkest,
      950: cascadeFigmaVariables.redDarkest,
    },
    gold: {
      50: cascadeFigmaVariables.goldLightest,
      100: cascadeFigmaVariables.goldLighter,
      200: cascadeFigmaVariables.goldLight,
      300: cascadeFigmaVariables.gold,
      400: cascadeFigmaVariables.goldDark,
      500: cascadeFigmaVariables.goldDarker,
      600: cascadeFigmaVariables.goldDarker,
      700: cascadeFigmaVariables.goldDarkest,
      800: cascadeFigmaVariables.goldDarkest,
      900: cascadeFigmaVariables.goldDarkest,
      950: cascadeFigmaVariables.goldDarkest,
    },
    teal: {
      50: cascadeFigmaVariables.tealLightest,
      100: cascadeFigmaVariables.tealLighter,
      200: cascadeFigmaVariables.tealLight,
      300: cascadeFigmaVariables.teal,
      400: cascadeFigmaVariables.tealDark,
      500: cascadeFigmaVariables.tealDarker,
      600: cascadeFigmaVariables.tealDarker,
      700: cascadeFigmaVariables.tealDarkest,
      800: cascadeFigmaVariables.tealDarkest,
      900: cascadeFigmaVariables.tealDarkest,
      950: cascadeFigmaVariables.tealDarkest,
    },
    yellow: {
      50: cascadeFigmaVariables.goldLightest,
      100: cascadeFigmaVariables.goldLighter,
      200: cascadeFigmaVariables.goldLight,
      300: cascadeFigmaVariables.gold,
      400: cascadeFigmaVariables.goldDark,
      500: cascadeFigmaVariables.goldDarker,
      600: cascadeFigmaVariables.goldDarker,
      700: cascadeFigmaVariables.goldDarkest,
      800: cascadeFigmaVariables.goldDarkest,
      900: cascadeFigmaVariables.goldDarkest,
      950: cascadeFigmaVariables.goldDarkest,
    },
  },
  semantic: {
    primary: {
      50: cascadeFigmaVariables.blueLightest10,
      100: cascadeFigmaVariables.blueLightest10,
      200: cascadeFigmaVariables.blueLightest,
      300: cascadeFigmaVariables.blueLighter,
      400: cascadeFigmaVariables.blueLight,
      500: cascadeFigmaVariables.blue,
      600: cascadeFigmaVariables.blueDark,
      700: cascadeFigmaVariables.blueDarker,
      800: cascadeFigmaVariables.blueDarker,
      900: cascadeFigmaVariables.blueDarker,
      950: cascadeFigmaVariables.blueDarkest,
    },
    secondary: {
      50: cascadeFigmaVariables.purpleLightest,
      100: cascadeFigmaVariables.purpleLighter,
      200: cascadeFigmaVariables.purpleLight,
      300: cascadeFigmaVariables.purple,
      400: cascadeFigmaVariables.purpleDark,
      500: cascadeFigmaVariables.purpleDarker,
      600: cascadeFigmaVariables.purpleDarker,
      700: cascadeFigmaVariables.purpleDarkest,
      800: cascadeFigmaVariables.purpleDarkest,
      900: cascadeFigmaVariables.purpleDarkest,
      950: cascadeFigmaVariables.purpleDarkest,
    },
    danger: {
      50: cascadeFigmaVariables.redLightest,
      100: cascadeFigmaVariables.redLighter,
      200: cascadeFigmaVariables.redLight,
      300: cascadeFigmaVariables.red,
      400: cascadeFigmaVariables.redDark,
      500: cascadeFigmaVariables.redDarker,
      600: cascadeFigmaVariables.redDarker,
      700: cascadeFigmaVariables.redDarkest,
      800: cascadeFigmaVariables.redDarkest,
      900: cascadeFigmaVariables.redDarkest,
      950: cascadeFigmaVariables.redDarkest,
    },
    warning: {
      50: cascadeFigmaVariables.goldLightest,
      100: cascadeFigmaVariables.goldLighter,
      200: cascadeFigmaVariables.goldLight,
      300: cascadeFigmaVariables.gold,
      400: cascadeFigmaVariables.goldDark,
      500: cascadeFigmaVariables.goldDarker,
      600: cascadeFigmaVariables.goldDarker,
      700: cascadeFigmaVariables.goldDarkest,
      800: cascadeFigmaVariables.goldDarkest,
      900: cascadeFigmaVariables.goldDarkest,
      950: cascadeFigmaVariables.goldDarkest,
    },
    success: {
      50: cascadeFigmaVariables.tealLightest,
      100: cascadeFigmaVariables.tealLighter,
      200: cascadeFigmaVariables.tealLight,
      300: cascadeFigmaVariables.teal,
      400: cascadeFigmaVariables.tealDark,
      500: cascadeFigmaVariables.tealDarker,
      600: cascadeFigmaVariables.tealDarker,
      700: cascadeFigmaVariables.tealDarkest,
      800: cascadeFigmaVariables.tealDarkest,
      900: cascadeFigmaVariables.tealDarkest,
      950: cascadeFigmaVariables.tealDarkest,
    },
    info: {
      50: cascadeFigmaVariables.purpleLightest,
      100: cascadeFigmaVariables.purpleLighter,
      200: cascadeFigmaVariables.purpleLight,
      300: cascadeFigmaVariables.purple,
      400: cascadeFigmaVariables.purpleDark,
      500: cascadeFigmaVariables.purpleDarker,
      600: cascadeFigmaVariables.purpleDarker,
      700: cascadeFigmaVariables.purpleDarkest,
      800: cascadeFigmaVariables.purpleDarkest,
      900: cascadeFigmaVariables.purpleDarkest,
      950: cascadeFigmaVariables.purpleDarkest,
    },
    colorScheme: {
      light: {
          surface: {
            50: cascadeFigmaVariables.greyLightest,
            100: cascadeFigmaVariables.greyLighter,
            200: cascadeFigmaVariables.greyLight,
            300: cascadeFigmaVariables.grey,
            400: cascadeFigmaVariables.greyDark,
            500: cascadeFigmaVariables.greyDarkest,
            600: cascadeFigmaVariables.greyDarkest,
            700: cascadeFigmaVariables.greyDarkest,
            800: cascadeFigmaVariables.greyDarkest,
            900: cascadeFigmaVariables.greyDarkest,
            950: cascadeFigmaVariables.greyDarkest,
          }
        }
      }
  },
  
});

export { Cascade, cascadeFigmaVariables };
