export const memberData = {
    "id": 1,
    "name": "All Members",
    "metadata": null,
    "totalCount": 145561,
    "activeCount": 145561,
    "allAccessibleMbrCount": 145561,
    "rows": [
        {
            "member_id": 4037325,
            "source_member_nbr": "173335",
            "first_name": "SERGIO",
            "last_name": "AAMOT",
            "age": 2,
            "gender": "MALE",
            "language": "Spanish",
            "line_of_business": "MEDICAID",
            "state": "UNKNOWN",
            "county": "UNKNOWN",
            "phone_nbr": "(555) 262-7227",
            "address_1": "522 Main St",
            "dob": "2022-07-17",
            "provider_group_1_name": null,
            "provider_group_2_name": null
        },
        {
            "member_id": 3568326,
            "source_member_nbr": "42123",
            "first_name": "TEDDY",
            "last_name": "AANENSON",
            "age": 36,
            "gender": "MALE",
            "language": "English",
            "line_of_business": "MEDICAID",
            "state": "MA",
            "county": "HAMPDEN",
            "phone_nbr": "(555) 220-3676",
            "address_1": "552 Main St",
            "dob": "1988-12-01",
            "provider_group_1_name": "HOLYOKE HEALTH CENTER",
            "provider_group_2_name": "HARMONY MEDICAL GROUP"
        },
        {
            "member_id": 807350,
            "source_member_nbr": "125466",
            "first_name": "ULYSSES",
            "last_name": "AANENSON",
            "age": 27,
            "gender": "FEMALE",
            "language": "English",
            "line_of_business": "MEDICAID",
            "state": "MA",
            "county": "BERKSHIRE",
            "phone_nbr": "(555) 293-4971",
            "address_1": "943 Main St",
            "dob": "1997-06-28",
            "provider_group_1_name": "THE STOCKBRIDGE CLINIC",
            "provider_group_2_name": "INFINITY MEDICAL PARTNERS"
        },
        {
            "member_id": 1564470,
            "source_member_nbr": "167125",
            "first_name": "EULA",
            "last_name": "ABATI",
            "age": 6,
            "gender": "MALE",
            "language": "English",
            "line_of_business": "MEDICAID",
            "state": "MA",
            "county": "ESSEX",
            "phone_nbr": "(555) 280-5118",
            "address_1": "926 Main St",
            "dob": "2018-10-03",
            "provider_group_1_name": "THE HAVERHILL CLINIC",
            "provider_group_2_name": "PEAK PERFORMANCE MEDICAL GROUP"
        },
        {
            "member_id": 260266,
            "source_member_nbr": "71749",
            "first_name": "KRYSTA",
            "last_name": "ABBASSI",
            "age": 26,
            "gender": "FEMALE",
            "language": "English",
            "line_of_business": "COMMERCIAL",
            "state": "MA",
            "county": "PLYMOUTH",
            "phone_nbr": "(555) 229-8983",
            "address_1": "460 Main St",
            "dob": "1998-02-15",
            "provider_group_1_name": "SOUTH SHORE PRIMARY CARE",
            "provider_group_2_name": "NEW HORIZONS MEDICAL GROUP"
        },
        {
            "member_id": 1481280,
            "source_member_nbr": "133359",
            "first_name": "OTILIA",
            "last_name": "ABBASSI",
            "age": 12,
            "gender": "MALE",
            "language": "English",
            "line_of_business": "MEDICAID",
            "state": "MA",
            "county": "BERKSHIRE",
            "phone_nbr": "(555) 302-2917",
            "address_1": "525 Main St",
            "dob": "2012-03-06",
            "provider_group_1_name": "GREAT BARRINGTON PRIMARY CARE",
            "provider_group_2_name": "INFINITY MEDICAL PARTNERS"
        },
        {
            "member_id": 38371,
            "source_member_nbr": "8859",
            "first_name": "ARMANDO",
            "last_name": "ABDALLAH",
            "age": 52,
            "gender": "FEMALE",
            "language": "English",
            "line_of_business": "COMMERCIAL",
            "state": "MA",
            "county": "MIDDLESEX",
            "phone_nbr": "(555) 229-4502",
            "address_1": "191 Main St",
            "dob": "1972-09-13",
            "provider_group_1_name": "ARLINGTON FAMILY CARE",
            "provider_group_2_name": "GLOBAL MEDICAL ASSOCIATES"
        },
        {
            "member_id": 190413,
            "source_member_nbr": "51423",
            "first_name": "RUDY",
            "last_name": "ABELAR",
            "age": 54,
            "gender": "MALE",
            "language": "English",
            "line_of_business": "COMMERCIAL, MEDICAID",
            "state": "RI",
            "county": "PROVIDENCE",
            "phone_nbr": "(555) 217-4288",
            "address_1": "404 Main St",
            "dob": "1970-10-02",
            "provider_group_1_name": "HEALTH CHOICE PROVIDENCE",
            "provider_group_2_name": "ZENITH MEDICAL PARTNERS"
        },
        {
            "member_id": 332364,
            "source_member_nbr": "92270",
            "first_name": "JONELLE",
            "last_name": "ABELARDO",
            "age": 83,
            "gender": "MALE",
            "language": "English",
            "line_of_business": "MEDICARE",
            "state": "MA",
            "county": "MIDDLESEX",
            "phone_nbr": "(555) 231-8059",
            "address_1": "645 Main St",
            "dob": "1941-11-18",
            "provider_group_1_name": "LEXINGTON MEDICAL ASSOCIATES",
            "provider_group_2_name": "QUANTUM MEDICAL PARTNERS"
        },
        {
            "member_id": 349766,
            "source_member_nbr": "95708",
            "first_name": "JOSETTE",
            "last_name": "ABELARDO",
            "age": 65,
            "gender": "MALE",
            "language": "English",
            "line_of_business": "COMMERCIAL",
            "state": "MA",
            "county": "MIDDLESEX",
            "phone_nbr": "(555) 250-1755",
            "address_1": "963 Main St",
            "dob": "1959-03-11",
            "provider_group_1_name": "ARLINGTON FAMILY CARE",
            "provider_group_2_name": "GLOBAL MEDICAL ASSOCIATES"
        },
        {
            "member_id": 2998637,
            "source_member_nbr": "105992",
            "first_name": "LORALEE",
            "last_name": "ABELARDO",
            "age": 77,
            "gender": "FEMALE",
            "language": "English",
            "line_of_business": "MEDICARE",
            "state": "MA",
            "county": "NORFOLK",
            "phone_nbr": "(555) 262-3228",
            "address_1": "141 Main St",
            "dob": "1947-10-26",
            "provider_group_1_name": "NORFOLK PRIME HEALTH",
            "provider_group_2_name": "HARMONY MEDICAL GROUP"
        },
        {
            "member_id": 906650,
            "source_member_nbr": "128894",
            "first_name": "ROSALIND",
            "last_name": "ABELARDO",
            "age": 47,
            "gender": "FEMALE",
            "language": "English",
            "line_of_business": "MEDICAID",
            "state": "MA",
            "county": "BERKSHIRE",
            "phone_nbr": "(555) 228-8438",
            "address_1": "516 Main St",
            "dob": "1977-05-28",
            "provider_group_1_name": "THE STOCKBRIDGE CLINIC",
            "provider_group_2_name": "INFINITY MEDICAL PARTNERS"
        },
        {
            "member_id": 415530,
            "source_member_nbr": "108983",
            "first_name": "FABIAN",
            "last_name": "ABELE",
            "age": 78,
            "gender": "FEMALE",
            "language": "English",
            "line_of_business": "MEDICARE",
            "state": "MA",
            "county": "BERKSHIRE",
            "phone_nbr": "(555) 242-2808",
            "address_1": "491 Main St",
            "dob": "1946-03-11",
            "provider_group_1_name": "THE LEE FAMILY HEALTH CENTER",
            "provider_group_2_name": "NORTHSTAR MEDICAL GROUP"
        },
        {
            "member_id": 1305776,
            "source_member_nbr": "143459",
            "first_name": "HWA",
            "last_name": "ABETE",
            "age": 76,
            "gender": "FEMALE",
            "language": "English",
            "line_of_business": "MEDICARE",
            "state": "MA",
            "county": "NORFOLK",
            "phone_nbr": "(555) 248-1636",
            "address_1": "861 Main St",
            "dob": "1948-06-05",
            "provider_group_1_name": "QUINCY ELITE MEDICAL - PRIMARY CARE",
            "provider_group_2_name": "QUINCY ELITE MEDICAL"
        },
        {
            "member_id": 205853,
            "source_member_nbr": "60687",
            "first_name": "CECIL",
            "last_name": "ABLER",
            "age": 47,
            "gender": "FEMALE",
            "language": "English",
            "line_of_business": "COMMERCIAL",
            "state": "CT",
            "county": "WINDHAM",
            "phone_nbr": "(555) 227-8542",
            "address_1": "2 Main St",
            "dob": "1977-03-30",
            "provider_group_1_name": "VASSAR HEALTH",
            "provider_group_2_name": "HEALTH CARE CONNECTION"
        }
    ],
    "asOfDate": "2024-11-30T00:00:00.000Z",
    "query": "SELECT member_id\n\t, source_member_nbr\n\t, first_name\n\t, last_name\n\t, age\n\t, gender\n\t, language\n\t, line_of_business\n\t, state\n\t, county\n\t, phone_nbr\n\t, address_1\n\t, dob\n\t, provider_group_1_name\n\t, provider_group_2_name\n \t FROM sg.vw_member_attributes\n ORDER BY \n\t order_id ASC NULLS LAST\n OFFSET ($1) LIMIT ($2);"
}