import { channel } from 'node:diagnostics_channel';

export enum Status {
  Published = 'Active',
  Draft = 'Complete',
  Archived = 'Launched',
}

export enum Channel {
  Online = 'Email',
  InPerson = 'IVR',
  LiveCall = 'Live Call',
  SMS = 'SMS',
}

export const programData = [
  {
    status: Status.Draft,
    channel: [Channel.LiveCall, Channel.Online],
    trackedOutcome:
      'Voluntary Disenrollment within 3 months following outreach',
    title: 'Health Outcomes Survey',
    description:
      'Target high risk members likely to leave the plan to minimize disenrollment',
    startDate: '01/12/2024',
    endDate: '03/12/2025',
    dataAsOf: '01/12/2024',
    engagementRate: 10.77,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is ahead of benchmarks!',
    memberList: 127703,
    engaged: 1243,
    didNotEngage: 1.2,
    unableToReach: 2.83,
    optedOut: 1.68,
  },
  {
    status: Status.Published,
    channel: Channel.InPerson,
    trackedOutcome:
      'Voluntary Disenrollment within 3 months following outreach',
    title: 'Establishing Care with a Primary Care Physician',
    startDate: '01/12/2024',
    endDate: '03/12/2025',
    dataAsOf: '01/12/2024',
    engagementRate: 57.84,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is ahead of benchmarks!',
    memberList: 127703,
    engaged: 450,
    didNotEngage: 1.2,
    unableToReach: 2.83,
    optedOut: 3.68,
  },
  {
    status: Status.Published,
    channel: Channel.Online,
    trackedOutcome:
      'Voluntary Disenrollment within 3 months following outreach',
    title: 'Breast Cancer Screening',
    description:
      'Target high risk members likely to leave the plan to minimize disenrollment',
    startDate: '01/12/2024',
    endDate: '03/12/2025',
    dataAsOf: '01/12/2024',
    engagementRate: 70.77,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is behind benchmarks!',
    memberList: 24206,
    engaged: 10293,
    didNotEngage: 1.2,
    unableToReach: 2.83,
    optedOut: 3.71,
  },
  {
    status: Status.Published,
    channel: Channel.LiveCall,
    trackedOutcome:
      'Voluntary Disenrollment within 3 months following outreach',
    title: 'Health Outcomes Survey',
    description:
      'Target high risk members likely to leave the plan to minimize disenrollment',
    startDate: '01/12/2024',
    endDate: '03/12/2025',
    dataAsOf: '01/12/2024',
    engagementRate: 50.77,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is ahead of benchmarks!',
    memberList: 127703,
    engaged: 1243,
    didNotEngage: 1.2,
    unableToReach: 2.83,
    optedOut: 1.68,
  },
  {
    status: Status.Published,
    channel: Channel.InPerson,
    trackedOutcome:
      'Voluntary Disenrollment within 3 months following outreach',
    title: 'Establishing Care with a Primary Care Physician',
    startDate: '01/12/2024',
    endDate: '03/12/2025',
    dataAsOf: '01/12/2024',
    engagementRate: 57.84,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is ahead of benchmarks!',
    memberList: 127703,
    engaged: 450,
    didNotEngage: 1.2,
    unableToReach: 2.83,
    optedOut: 3.68,
  },
  {
    status: Status.Published,
    channel: Channel.Online,
    trackedOutcome:
      'Voluntary Disenrollment within 3 months following outreach',
    title: 'Breast Cancer Screening',
    description:
      'Target high risk members likely to leave the plan to minimize disenrollment',
    startDate: '01/12/2024',
    endDate: '03/12/2025',
    dataAsOf: '01/12/2024',
    engagementRate: 70.77,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is behind benchmarks!',
    memberList: 24206,
    engaged: 10293,
    didNotEngage: 1.2,
    unableToReach: 2.83,
    optedOut: 3.71,
  },
  {
    status: Status.Published,
    channel: Channel.Online,
    trackedOutcome:
      'Voluntary Disenrollment within 3 months following outreach',
    title: 'Breast Cancer Screening',
    description:
      'Target high risk members likely to leave the plan to minimize disenrollment',
    startDate: '01/12/2024',
    endDate: '03/12/2025',
    dataAsOf: '01/12/2024',
    engagementRate: 70.77,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is behind benchmarks!',
    memberList: 24206,
    engaged: 10293,
    didNotEngage: 1.2,
    unableToReach: 2.83,
    optedOut: 3.71,
  },
];
