import { channel } from 'node:diagnostics_channel';

export enum Status {
  Active = 'Active',
  Complete = 'Complete',
  Launched = 'Recently Launched',
}

export enum Channel {
  Online = 'Email',
  InPerson = 'IVR',
  LiveCall = 'Live Call',
  SMS = 'SMS',
}

export const programData = [
  {
    status: Status.Launched,
    channel: Channel.Online,
    trackedOutcome:
      'Breast Cancer Screening within 3 months following outreach',
    title: 'Breast Cancer Screening',
    description:
      'Closing gaps in care for breast cancer screening',
    startDate: '01/12/2024',
    endDate: '03/12/2025',
    dataAsOf: '01/12/2024',
    engagementRate: 1.77,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is behind benchmarks!',
    memberList: 24206,
    engaged: 10293,
    didNotEngage: 1.2,
    unableToReach: 2.83,
    optedOut: 3.71,
  },
  {
    status: Status.Active,
    channel: Channel.InPerson,
    trackedOutcome:
      'Voluntary Disenrollment within 3 months following outreach',
    title: 'Health Outcomes Survey',
    startDate: '01/12/2024',
    endDate: '03/12/2025',
    dataAsOf: '01/12/2024',
    engagementRate: 57.84,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is ahead of benchmarks!',
    memberList: 127703,
    engaged: 450,
    didNotEngage: 1.2,
    unableToReach: 2.83,
    optedOut: 3.68,
  },
  {
    status: Status.Complete,
    channel: [Channel.LiveCall, Channel.Online],
    trackedOutcome:
      '7-Day ED Visit Follow up rate',
    title: 'Post ED Visit Follow up with a PCP',
    description:
      'Target high risk members likely to leave the plan to minimize disenrollment',
    startDate: '01/12/2024',
    endDate: '03/12/2025',
    dataAsOf: '01/12/2024',
    engagementRate: 10.77,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is ahead of benchmarks!',
    memberList: 127703,
    engaged: 1243,
    didNotEngage: 1.2,
    unableToReach: 2.83,
    optedOut: 1.68,
  },
  {
    status: Status.Active,
    channel: Channel.LiveCall,
    trackedOutcome:
      'Diabetes A1C testing within 6 months following outreach',
    title: 'Diabetes Care Management',
    description:
      'Improve diabetes outcomes through regular A1C testing and care coordination',
    startDate: '03/15/2024',
    endDate: '09/15/2025',
    dataAsOf: '12/01/2024',
    engagementRate: 42.3,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is meeting benchmarks',
    memberList: 8547,
    engaged: 3615,
    didNotEngage: 2.1,
    unableToReach: 4.2,
    optedOut: 1.8,
  },
  {
    status: Status.Active,
    channel: Channel.SMS,
    trackedOutcome:
      'Annual wellness visit completion within 90 days',
    title: 'Annual Wellness Visit Outreach',
    description:
      'Encourage preventive care through annual wellness visits for Medicare beneficiaries',
    startDate: '01/01/2024',
    endDate: '12/31/2024',
    dataAsOf: '12/01/2024',
    engagementRate: 68.9,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is ahead of benchmarks!',
    memberList: 45230,
    engaged: 31173,
    didNotEngage: 1.5,
    unableToReach: 3.1,
    optedOut: 2.4,
  },
  {
    status: Status.Active,
    channel: Channel.Online,
    trackedOutcome:
      'Medication adherence improvement within 60 days',
    title: 'Hypertension Medication Adherence',
    description:
      'Support members with hypertension to maintain consistent medication regimens',
    startDate: '06/01/2024',
    endDate: '05/31/2025',
    dataAsOf: '12/01/2024',
    engagementRate: 55.2,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is ahead of benchmarks!',
    memberList: 12894,
    engaged: 7118,
    didNotEngage: 2.8,
    unableToReach: 3.5,
    optedOut: 1.9,
  },
  {
    status: Status.Active,
    channel: [Channel.LiveCall, Channel.Online],
    trackedOutcome:
      'Colorectal cancer screening completion within 4 months',
    title: 'Colorectal Cancer Screening Initiative',
    description:
      'Increase screening rates for colorectal cancer among eligible members aged 50-75',
    startDate: '02/01/2024',
    endDate: '01/31/2025',
    dataAsOf: '12/01/2024',
    engagementRate: 38.7,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is behind benchmarks',
    memberList: 18652,
    engaged: 7218,
    didNotEngage: 3.2,
    unableToReach: 4.8,
    optedOut: 2.1,
  },
  {
    status: Status.Complete,
    channel: Channel.InPerson,
    trackedOutcome:
      'Postpartum care visit within 21-56 days after delivery',
    title: 'Maternal Health Follow-up Program',
    description:
      'Ensure new mothers receive timely postpartum care to improve maternal health outcomes',
    startDate: '04/01/2024',
    endDate: '10/31/2024',
    dataAsOf: '11/15/2024',
    engagementRate: 73.4,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is ahead of benchmarks!',
    memberList: 2847,
    engaged: 2089,
    didNotEngage: 1.8,
    unableToReach: 2.1,
    optedOut: 0.9,
  },
  {
    status: Status.Launched,
    channel: Channel.SMS,
    trackedOutcome:
      'Flu vaccination completion within 3 months of outreach',
    title: 'Seasonal Influenza Vaccination Campaign',
    description:
      'Increase flu vaccination rates among high-risk members during flu season',
    startDate: '09/01/2024',
    endDate: '03/31/2025',
    dataAsOf: '12/01/2024',
    engagementRate: 29.6,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is behind benchmarks',
    memberList: 67432,
    engaged: 19956,
    didNotEngage: 4.1,
    unableToReach: 5.2,
    optedOut: 3.8,
  },
  {
    status: Status.Active,
    channel: [Channel.LiveCall, Channel.SMS],
    trackedOutcome:
      'Emergency department visit reduction by 20% within 6 months',
    title: 'High-Utilizer Care Coordination',
    description:
      'Provide intensive case management for members with frequent ED visits',
    startDate: '05/15/2024',
    endDate: '11/15/2025',
    dataAsOf: '12/01/2024',
    engagementRate: 81.2,
    engagementRateTitle: 'Engagement Rate',
    engagementRateSubtitle: 'Your program is ahead of benchmarks!',
    memberList: 1523,
    engaged: 1237,
    didNotEngage: 0.8,
    unableToReach: 1.4,
    optedOut: 0.6,
  },
];
